/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  EuiAccordion,
  EuiCodeBlock,
  EuiEmptyPrompt,
  EuiLoadingContent,
  EuiSpacer,
  EuiText,
  EuiMarkdownFormat,
  EuiHorizontalRule,
} from '@elastic/eui';
import React from 'react';
import { useFetchAgentFrameworkTraces } from '../hooks/use_fetch_agentframework_traces';

interface AgentFrameworkTracesProps {
  interactionId: string;
}

export const AgentFrameworkTraces: React.FC<AgentFrameworkTracesProps> = (props) => {
  const { data: traces, loading, error } = useFetchAgentFrameworkTraces(props.interactionId);

  if (loading) {
    return (
      <>
        <EuiText>Loading...</EuiText>
        <EuiLoadingContent lines={10} />
      </>
    );
  }
  if (error) {
    return (
      <EuiEmptyPrompt
        iconType="alert"
        iconColor="danger"
        title={<h2>Error loading details</h2>}
        body={error.toString()}
      />
    );
  }
  if (!traces?.length) {
    return <EuiText>Data not available.</EuiText>;
  }

  const question = traces[traces.length - 1].input;
  const result = traces[traces.length - 1].output;
  const questionAndResult = `# How was this generated
#### Question
${question}
#### Result
${result}
`;

  return (
    <>
      <EuiMarkdownFormat>{questionAndResult}</EuiMarkdownFormat>

      <EuiSpacer size="l" />

      <EuiText>
        <h3>Response</h3>
      </EuiText>
      {traces
        // if origin exists, it indicates that the trace was generated by a tool, we only show the non-empty traces of tools
        .filter((trace) => trace.origin && (trace.input || trace.output))
        .map((trace, i) => {
          const stepContent = `Step ${i + 1} - ${trace.origin}`;
          return (
            <div key={trace.interactionId}>
              <EuiSpacer size="s" />
              <EuiAccordion id={stepContent} buttonContent={stepContent}>
                {trace.input && (
                  <EuiCodeBlock fontSize="m" paddingSize="s">
                    Input: {trace.input}
                  </EuiCodeBlock>
                )}
                {trace.output && (
                  <EuiCodeBlock fontSize="m" paddingSize="s">
                    Output: {trace.output}
                  </EuiCodeBlock>
                )}
              </EuiAccordion>
              <EuiHorizontalRule margin="xs" />
            </div>
          );
        })}
    </>
  );
};
